### ISSUE TITLE
rueidis v0.0.41 now allows preparation of bulk commands

### ISSUE THREAD

**Issue by rueian** [ujunglangit-id/redis-timeseries-bench#1]
Hi @ujunglangit-id,

I saw you were trying to do bulk insertion with rueidis by spreading chunks into many gorutines.

I understand that the approach was tricky and hard to code. 

Now, with rueidis v0.0.41, there is a much easier way to do bulk insertion, for example:

```golang
func (b *Bench) InsertToRedis() {
	if err := b.RedisClient.Dedicated(func(client rueidis.DedicatedClient) error {
		cmds := make(rueidis.Commands, 0, len(b.PayloadData)/2)
		for i := 0; i < len(b.PayloadData); i += 2 {
			cmd := b.RedisClient.B().TsMadd().KeyTimestampValue()
			cmd = cmd.KeyTimestampValue(b.Key, time.Now().UnixNano(), b.PayloadData[i+0].Volume)
			cmd = cmd.KeyTimestampValue(b.Key, time.Now().UnixNano(), b.PayloadData[i+1].Volume)
			cmds = append(cmds, cmd.Build())
		}
		for _, resp := range client.DoMulti(context.Background(), cmds...) {
			if err := resp.Error(); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		log.Error().Msgf("error add timeseries %#v", err)
	}
}
```

Please let me know what would you think about that and thank you for trying out rueidis.

**Comment by titikterang** [comment]
woah, hi @rueian 
will try with that. it looks much more simpler, rather than manually splitting into goroutines. 

i've done some test few times, and the throughput is pretty stable on my machine, around 450ms to 480ms for 600k rows bulk insert. 

thanks in advance for the suggestion.
